#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/gooddeeds_backbone
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  devtools:
#    restart:
#      enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gooddeeds_backbone
    username: blue
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true

  devtools:
    restart:
      enabled: false

jwt:
  secret: ${JWT_SECRET:THIS_IS_A_DEMO_SECRET_KEY_CHANGE_IT_LATER_123456}
  expiration: ${JWT_EXPIRATION:86400000}

server:
  tomcat:
    threads:
      max: 200
      min-spare: 20
    accept-count: 100
    max-connections: 10000
